on:
  push:
    branches:
      - expansion
      - 'experiment/*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        shell: cmd
        run: |
          cd src
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./msvcbuild.bat gc64

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lje-${{github.sha}}
          path: |
            src/lje-w64.dll
            src/lje-launcher.exe
